### ISSUE TITLE
Algumas alterações pendentes

### ISSUE THREAD

**Issue by uselessdev** [coderwebschool/coderwebschool.github.io#1]
- [x] Trocar imagem da página inicial
- [x] Adicionar ID do google analytics
- [x] Adicionar username do DISQUS pra habilitar os comentários 

@flyingluscas se você providenciar essas informações eu mesmo posso alterar :smile:

**Comment by flyingluscas** [comment]
@uselessdev ID do Google Analytics  : UA-87322769-1

**Comment by flyingluscas** [comment]
@uselessdev username do DISQUS : coderwebschool
